version: "3"

env:
  STATIC_DIR: "static"

tasks:
  # The `build:` tasks below are used together for "production" builds of your project
  build:templ:
    cmds:
      - templ generate -v

  build:styles:
    cmds:
      - tailwindcss -i input.css -o $STATIC_DIR/output.css

  build:
    cmds:
      - go build -o counter *.go
    deps:
      - build:styles
      - build:templ

  # Use this task to debug your project with the delve debugger
  debug:
    cmds:
      - go run github.com/go-delve/delve/cmd/dlv@v1.23.1 exec ./counter
    deps:
      - build

  # The `live:` tasks below are used together for "dev" builds, and will hot-reload your entire project when there are code changes
  live:templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8080" --proxybind="localhost" --cmd="go run ."

  live:styles:
    cmds:
      - tailwindcss -i input.css -o $STATIC_DIR/output.css --watch

  live:
    deps:
      - live:templ
      - live:styles

  run:
    cmds:
      - ./counter
    deps:
      - build
